services:
  autonomous_system:
    build: ./docker/autonomous_system
    image: imgs/autonomous_system
    container_name: autonomous_system
    network_mode: host
    stdin_open: true
    tty: true
    user: rosdev
    privileged: true
    ipc: host
    pid: host
    volumes:
      - /dev:/dev
      - ./ws:/home/rosdev/ws
  ardupilot_gazebo:
    build: ./docker/ardupilot_gazebo
    image: imgs/ardupilot_gazebo
    container_name: ardupilot_gazebo
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    ipc: host
    pid: host
    environment:
      - DISPLAY=$DISPLAY
    volumes:
        - /dev:/dev
        - /dev/video*:/dev/video*
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
    deploy:
      resources:
          reservations:
              devices:
                  - driver: nvidia
                    count: all
                    capabilities: [gpu]
              memory: 12g